import assert from "node:assert/strict";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

import { executeAssistantActions } from "../assistant/assistantActionExecutor.js";
import { lintCanvasSpatial } from "../assistant/canvasTidy.js";
import { buildDirectorBrainCanvasPlan } from "./directorBrainService.js";
import { loadDirectorMemoryExport } from "./directorMemoryExportLoader.js";

// Cross-repo contract test: this golden fixture is GENERATED by
// QMAI's real export code (director-export.live.spec.ts), not written
// by hand. If either side changes the qmai-director-export/v1
// contract, this test breaks here instead of in production.
const GOLDEN_PATH = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "__fixtures__/qmai-director-export.golden.json",
);

function createGraphStore() {
  const nodes = [];
  const edges = [];
  return {
    nodes,
    edges,
    addNode(node) { nodes.push(node); return node; },
    addEdge(edge) { edges.push(edge); return edge; },
    updateNodeData(nodeId, patch) {
      const node = nodes.find((item) => item.id === nodeId);
      if (node) node.data = { ...(node.data || {}), ...(patch || {}) };
    },
    setSelectedNodes() {},
  };
}

test("golden contract: the QMAI-generated envelope loads as director memory", async () => {
  const memory = await loadDirectorMemoryExport(GOLDEN_PATH);

  assert.equal(memory.project.name, "旧伞告别");
  assert.equal(memory.entries.length >= 2, true);
  assert.equal(memory.entries.some((entry) => entry.text.includes("湿透")), true);
  assert.equal(memory.flowId, "flow-flywheel-round-2");
  assert.equal(typeof memory.exportedAt, "string");
  assert.equal(Number.isNaN(new Date(memory.exportedAt).getTime()), false);
  assert.equal(Array.isArray(memory.knowledgeCards), true);
  assert.equal(memory.artifacts.storyboard.schemaVersion, "director-storyboard/v1");
  assert.equal(memory.artifacts.prompts.length, 6);
  assert.equal(memory.artifacts.continuityReport.status, "block");
  assert.equal(JSON.stringify(memory).includes("D:\\\\tmp"), false);
});

test("golden contract: envelope consumers validate symmetrically with the producer", async () => {
  const raw = JSON.parse(await fs.readFile(GOLDEN_PATH, "utf-8"));

  await assert.rejects(
    loadDirectorMemoryExport("D:\\virtual\\bad-project-id.json", {
      readFile: async () => JSON.stringify({ ...raw, project: { id: "p/../escape", name: "x" } }),
    }),
    /path separators|control/,
  );
  await assert.rejects(
    loadDirectorMemoryExport("D:\\virtual\\no-exported-at.json", {
      readFile: async () => JSON.stringify({ ...raw, exportedAt: undefined }),
    }),
    /exportedAt/,
  );
  await assert.rejects(
    loadDirectorMemoryExport("D:\\virtual\\bad-storyboard.json", {
      readFile: async () => JSON.stringify({ ...raw, artifacts: { ...raw.artifacts, storyboard: { schemaVersion: "director-storyboard/v1", shots: [] } } }),
    }),
    /storyboard/,
  );
  await assert.rejects(
    loadDirectorMemoryExport("D:\\virtual\\bad-continuity.json", {
      readFile: async () => JSON.stringify({ ...raw, artifacts: { ...raw.artifacts, continuityReport: { schemaVersion: "director-continuity-report/v1", status: "fine", issues: [] } } }),
    }),
    /continuityReport/,
  );
  await assert.rejects(
    loadDirectorMemoryExport("D:\\virtual\\bad-knowledge.json", {
      readFile: async () => JSON.stringify({ ...raw, knowledgeCards: [{ id: "", title: "" }] }),
    }),
    /knowledgeCards/,
  );
});

test("golden contract: envelope artifacts drive a gated plan through the real executor", async () => {
  const memory = await loadDirectorMemoryExport(GOLDEN_PATH);

  const plan = await buildDirectorBrainCanvasPlan({
    qmaiProjectPath: GOLDEN_PATH,
    storyboard: memory.artifacts.storyboard,
    prompts: memory.artifacts.prompts,
    continuityReport: memory.artifacts.continuityReport,
    flowId: memory.flowId,
  });

  // The real exported verdict (block) governs the plan.
  assert.equal(plan.status, "block");
  assert.equal(plan.verdicts[0].schemaVersion, "gate-verdict/v1");
  assert.equal(plan.verdicts[0].flowId, "flow-flywheel-round-2");
  assert.match(plan.verdicts[0].reasons[0].message, /旧伞|柜台/);

  const graphStore = createGraphStore();
  const result = await executeAssistantActions({ actions: plan.actions, graphStore });
  assert.equal(graphStore.nodes.filter((node) => node.type === "storyboard-script").length, 3);
  assert.equal(result.queuedGenerationNodeIds.length, 0);

  // S5 dogfooding acceptance: the director plan lands lint-clean -
  // shots in lanes, preps staged to their right, zero overlaps.
  const lint = lintCanvasSpatial(graphStore);
  assert.deepEqual(lint.overlaps, []);
  const shotNodes = graphStore.nodes.filter((node) => node.type === "storyboard-script");
  const shotRows = new Set(shotNodes.map((node) => node.y));
  assert.equal(shotRows.size, shotNodes.length);
});

test("golden contract: malformed envelopes fail closed", async () => {
  const raw = JSON.parse(await fs.readFile(GOLDEN_PATH, "utf-8"));
  const broken = { ...raw, memory: { entries: [] } };
  await assert.rejects(
    loadDirectorMemoryExport("D:\\virtual\\broken-export.json", {
      readFile: async () => JSON.stringify(broken),
    }),
    /entries/,
  );

  const wrongSchema = { ...raw, schemaVersion: "qmai-director-export/v9" };
  await assert.rejects(
    loadDirectorMemoryExport("D:\\virtual\\wrong-schema.json", {
      readFile: async () => JSON.stringify(wrongSchema),
    }),
    /schemaVersion/,
  );
});
